# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nim5HdJlp7ihJ8zse_wXqoELeZ0Xr4qT
"""

from pathlib import Path
import numpy as np
import os, shutil
import matplotlib.pyplot as plt

from PIL import Image

from tqdm.auto import tqdm

import torch
import torchvision
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder
from torchvision.transforms import transforms
import torch.optim as optim

from torchvision.models import resnet50, ResNet50_Weights

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

class resnet_feature_extractor(torch.nn.Module):
    def __init__(self):
        """This class extracts the feature maps from a pretrained Resnet model."""
        super(resnet_feature_extractor, self).__init__()
        self.model = resnet50(weights=ResNet50_Weights.DEFAULT)

        self.model.eval()
        for param in self.model.parameters():
            param.requires_grad = False



        # Hook to extract feature maps
        def hook(module, input, output) -> None:
            """This hook saves the extracted feature map on self.featured."""
            self.features.append(output)

        self.model.layer2[-1].register_forward_hook(hook)
        self.model.layer3[-1].register_forward_hook(hook)

    def forward(self, input):

        self.features = []
        with torch.no_grad():
            _ = self.model(input)

        self.avg = torch.nn.AvgPool2d(3, stride=1)
        fmap_size = self.features[0].shape[-2]         # Feature map sizes h, w
        self.resize = torch.nn.AdaptiveAvgPool2d(fmap_size)

        resized_maps = [self.resize(self.avg(fmap)) for fmap in self.features]
        patch = torch.cat(resized_maps, 1)            # Merge the resized feature maps
        patch = patch.reshape(patch.shape[1], -1).T   # Craete a column tensor

        return patch

!unzip -q "/content/Files.zip" -d "Carpet"

image = Image.open(r'/content/Carpet/carpet/test/color/000.png')
image = transform(image).unsqueeze(0).cuda()

backbone = resnet_feature_extractor().cuda()
feature = backbone(image)

# print(backbone.features[0].shape)
# print(backbone.features[1].shape)

print(feature.shape)

# plt.imshow(image[0].permute(1,2,0))

memory_bank =[]

folder_path = Path(r'/content/Carpet/carpet/train/good')

for pth in tqdm(folder_path.iterdir(),leave=False):

    with torch.no_grad():
        data = transform(Image.open(pth)).cuda().unsqueeze(0)
        features = backbone(data)
        memory_bank.append(features.cpu().detach())

memory_bank = torch.cat(memory_bank,dim=0).cuda()

selected_indices = np.random.choice(len(memory_bank), size=len(memory_bank)//10, replace=False)
memory_bank = memory_bank[selected_indices]

y_score=[]
folder_path = Path(r'/content/Carpet/carpet/train/good')

for pth in tqdm(folder_path.iterdir(),leave=False):
    data = transform(Image.open(pth)).cuda().unsqueeze(0)
    with torch.no_grad():
        features = backbone(data)
    distances = torch.cdist(features, memory_bank, p=2.0)
    dist_score, dist_score_idxs = torch.min(distances, dim=1)
    s_star = torch.max(dist_score)
    segm_map = dist_score.view(1, 1, 28, 28)

    y_score.append(s_star.cpu().numpy())

best_threshold = np.mean(y_score) + 2 * np.std(y_score)

plt.hist(y_score,bins=50)
plt.vlines(x=best_threshold,ymin=0,ymax=30,color='r')
plt.show()

y_score = []
y_true=[]

for classes in ['color','good','cut','hole','metal_contamination','thread']:
    folder_path = Path(r'/content/Carpet/carpet/test/{}'.format(classes))

    for pth in tqdm(folder_path.iterdir(),leave=False):

        class_label = pth.parts[-2]
        with torch.no_grad():
            test_image = transform(Image.open(pth)).cuda().unsqueeze(0)
            features = backbone(test_image)

        distances = torch.cdist(features, memory_bank, p=2.0)
        dist_score, dist_score_idxs = torch.min(distances, dim=1)
        s_star = torch.max(dist_score)
        segm_map = dist_score.view(1, 1, 28, 28)

        y_score.append(s_star.cpu().numpy())
        y_true.append(0 if class_label == 'good' else 1)

# plotting the y_score values which do not belong to 'good' class

y_score_nok = [score  for score,true in zip(y_score,y_true) if true==1]
plt.hist(y_score_nok,bins=50)
plt.vlines(x=best_threshold,ymin=0,ymax=30,color='r')
plt.show()

test_image = transform(Image.open(r'/content/Carpet/carpet/test/color/000.png')).cuda().unsqueeze(0)
features = backbone(test_image)

distances = torch.cdist(features, memory_bank, p=2.0)
dist_score, dist_score_idxs = torch.min(distances, dim=1)
s_star = torch.max(dist_score)
segm_map = dist_score.view(1, 1, 28, 28)

segm_map = torch.nn.functional.interpolate(     # Upscale by bi-linaer interpolation to match the original input resolution
                segm_map,
                size=(224, 224),
                mode='bilinear'
            )

plt.imshow(segm_map.cpu().squeeze(), cmap='jet')

from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, ConfusionMatrixDisplay, f1_score


# Calculate AUC-ROC score
auc_roc_score = roc_auc_score(y_true, y_score)
print("AUC-ROC Score:", auc_roc_score)

# Plot ROC curve
fpr, tpr, thresholds = roc_curve(y_true, y_score)
plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % auc_roc_score)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

f1_scores = [f1_score(y_true, y_score >= threshold) for threshold in thresholds]

# Select the best threshold based on F1 score
best_threshold = thresholds[np.argmax(f1_scores)]

print(f'best_threshold = {best_threshold}')

# Generate confusion matrix
cm = confusion_matrix(y_true, (y_score >= best_threshold).astype(int))
disp = ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=['OK','NOK'])
disp.plot()
plt.show()

import cv2, time
from IPython.display import clear_output

backbone.eval()

test_path = Path('/content/Carpet/carpet/test')

for path in test_path.glob('*/*.png'):

    fault_type = path.parts[-2]

    if fault_type in ['cut']:

        test_image = transform(Image.open(path)).cuda().unsqueeze(0)

        with torch.no_grad():
            features = backbone(test_image)
        # Forward pass
        distances = torch.cdist(features, memory_bank, p=2.0)
        dist_score, dist_score_idxs = torch.min(distances, dim=1)
        s_star = torch.max(dist_score)
        segm_map = dist_score.view(1, 1, 28, 28)
        segm_map = torch.nn.functional.interpolate(     # Upscale by bi-linaer interpolation to match the original input resolution
                    segm_map,
                    size=(224, 224),
                    mode='bilinear'
                ).cpu().squeeze().numpy()

        y_score_image = s_star.cpu().numpy()

        y_pred_image = 1*(y_score_image >= best_threshold)
        class_label = ['OK','NOK']


        plt.figure(figsize=(15,5))

        plt.subplot(1,3,1)
        plt.imshow(test_image.squeeze().permute(1,2,0).cpu().numpy())
        plt.title(f'fault type: {fault_type}')

        plt.subplot(1,3,2)
        heat_map = segm_map
        plt.imshow(heat_map, cmap='jet',vmin=best_threshold, vmax=best_threshold*2)
        plt.title(f'Anomaly score: {y_score_image / best_threshold:0.4f} || {class_label[y_pred_image]}')

        plt.subplot(1,3,3)
        plt.imshow((heat_map > best_threshold*1.25), cmap='gray')
        plt.title(f'segmentation map')

        plt.show()

!pip install torch_geometric

# imports (safe)
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from tqdm import tqdm
import math

# PyG imports
from torch_geometric.data import Data
from torch_geometric.nn import GATConv

# image resize
import torch.nn.functional as F

# device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("DEVICE:", device)

def build_patch_graph_from_features(patch_features, grid_h=None, grid_w=None, add_positional=True):
    """
    Convert patch_features (tensor [P, F]) into a PyG Data with grid adjacency.
    If grid_h/w not provided, try to infer a square grid (sqrt(P)).
    Returns: Data(x=node_features, edge_index)
    - adds optional positional coords as extra dims if add_positional=True
    """
    # patch_features: torch.Tensor [P, F]
    if not isinstance(patch_features, torch.Tensor):
        patch_features = torch.tensor(patch_features, dtype=torch.float)

    P, F = patch_features.shape

    if grid_h is None or grid_w is None:
        sq = int(math.sqrt(P))
        if sq * sq == P:
            grid_h = grid_w = sq
        else:
            # fallback: try factors. But default to P x 1 if cannot infer
            grid_h = P
            grid_w = 1

    # Node features start with the patch feature vector
    x = patch_features.clone().float()

    if add_positional:
        # add normalized (y,x) grid coordinates as extra two dims
        coords = []
        for idx in range(P):
            r = idx // grid_w
            c = idx % grid_w
            coords.append([r / (grid_h - 1) if grid_h>1 else 0.0, c / (grid_w - 1) if grid_w>1 else 0.0])
        coords = torch.tensor(coords, dtype=torch.float)
        x = torch.cat([x, coords], dim=1)  # new dim F+2

    # Build 4-neighbour grid adjacency (or 8-neighbour if you want)
    edge_list = []
    for r in range(grid_h):
        for c in range(grid_w):
            i = r * grid_w + c
            # right neighbour
            if c + 1 < grid_w:
                j = r * grid_w + (c+1)
                edge_list.append([i, j]); edge_list.append([j, i])
            # down neighbour
            if r + 1 < grid_h:
                j = (r+1) * grid_w + c
                edge_list.append([i, j]); edge_list.append([j, i])
            # (optional) diagonal neighbours - comment out if not wanted
            # if r+1 < grid_h and c+1 < grid_w:
            #     j = (r+1)*grid_w + (c+1)
            #     edge_list.append([i,j]); edge_list.append([j,i])

    if len(edge_list) == 0:
        edge_index = torch.empty((2,0), dtype=torch.long)
    else:
        edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous()

    data = Data(x=x, edge_index=edge_index)
    return data, (grid_h, grid_w)

class GATAutoEncoder(nn.Module):
    def __init__(self, in_dim, hidden_dim=256, latent_dim=128, heads=4, dropout=0.2):
        super().__init__()
        self.encoder1 = GATConv(in_dim, hidden_dim // heads, heads=heads, concat=True, dropout=dropout)
        self.encoder2 = GATConv(hidden_dim, latent_dim // heads, heads=heads, concat=True, dropout=dropout)

        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Linear(hidden_dim // 2, in_dim)
        )

    def forward(self, x, edge_index):
        h = torch.relu(self.encoder1(x, edge_index))
        h = torch.relu(self.encoder2(h, edge_index))
        recon = self.decoder(h)
        return recon, h

class GATAutoencoder(nn.Module):
    def __init__(self, in_channels, hidden_channels=128, dropout=0.2):
        super(GATAutoencoder, self).__init__()
        self.encoder = GATConv(in_channels, hidden_channels, heads=2, concat=True)
        self.decoder = nn.Sequential(
            nn.Linear(hidden_channels * 2, in_channels),
            nn.ReLU(),
            nn.Linear(in_channels, in_channels)
        )
        self.dropout = dropout

    def forward(self, x, edge_index):
        # Encoder
        x = F.elu(self.encoder(x, edge_index))
        x = F.dropout(x, p=self.dropout, training=self.training)
        # Decoder
        x_recon = self.decoder(x)
        return x_recon

def train_gat_autoencoder_on_normal_images(
    backbone_model,
    train_folder,
    model_save_path='gat_ae.pth',
    epochs=10,
    lr=5e-4,
    batch_size=8,
    grid_size=None,
    print_every=1
):
    backbone_model.eval()

    img_paths = list(Path(train_folder).glob('*.*'))
    if len(img_paths) == 0:
        raise ValueError(f"No images found in {train_folder}")

    # --- Build model shape from first image ---
    with torch.no_grad():
        img = Image.open(img_paths[0]).convert('RGB')
        inp = transform(img).unsqueeze(0).to(device)
        patch = backbone_model(inp)
        P, feat_dim = patch.shape

    in_dim = feat_dim + 2
    #gat_model = GATAutoEncoder(in_dim=in_dim, hidden_dim=256, latent_dim=128, dropout=0.2).to(device)
    gat_model = GATAutoencoder(in_channels=1538, hidden_channels=64).to(device)


    optimizer = optim.Adam(gat_model.parameters(), lr=lr, weight_decay=1e-5)
    mse_loss = nn.MSELoss()
    cosine = nn.CosineSimilarity(dim=1)

    for ep in range(epochs):
        epoch_loss = 0.0
        pbar = tqdm(img_paths, desc=f"Epoch {ep+1}/{epochs}")
        for p in pbar:
            img = Image.open(p).convert('RGB')
            inp = transform(img).unsqueeze(0).to(device)
            with torch.no_grad():
                patch = backbone_model(inp)

            data, (gh, gw) = build_patch_graph_from_features(
                patch.cpu(),
                grid_h=grid_size[0] if grid_size else None,
                grid_w=grid_size[1] if grid_size else None,
                add_positional=True
            )
            data.x = data.x.to(device)
            data.edge_index = data.edge_index.to(device)
            # Add Gaussian noise to input features (augmentation)


            # ---------- forward + loss ----------
            recon = gat_model(data.x, data.edge_index)

            feat_dim_local = patch.shape[1]
            recon_feat = recon[:, :feat_dim_local]
            target_feat = data.x[:, :feat_dim_local]

            mse = mse_loss(recon_feat, target_feat)
            cos_sim = torch.mean(1 - cosine(recon_feat, target_feat))
            loss = mse + 0.5 * cos_sim

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            pbar.set_postfix(loss=epoch_loss / (pbar.n if pbar.n > 0 else 1))

        if (ep + 1) % print_every == 0:
            print(f"Epoch {ep+1}/{epochs} avg loss: {epoch_loss/len(img_paths):.6f}")

    torch.save(gat_model.state_dict(), model_save_path)
    print("✅ Saved improved GAT-AE ->", model_save_path)
    return gat_model

    # Add Gaussian noise to input features (augmentation)
    noise = torch.randn_like(data.x) * 0.02  # small standard deviation
    noisy_input = data.x + noise
    recon = gat_model(noisy_input.to(device), data.edge_index)


# Usage example (do not overwrite backbone or memory_bank)
# gat_model = train_gat_autoencoder_on_normal_images(backbone, 'carpet/train/good', epochs=6)

gat_model = train_gat_autoencoder_on_normal_images(
    backbone,
    '/content/Carpet/carpet/train/good',
    epochs=25,
    lr=5e-4
)

def gat_ae_infer_image_heatmap(image_pil, backbone_model, gat_model, up_size=(224,224)):
    """
    image_pil: PIL.Image
    returns: segm_map_upsampled (H,W) as numpy array, per_patch_scores (P,)
    """
    backbone_model.eval()
    gat_model.eval()

    inp = transform(image_pil).unsqueeze(0).to(device)
    with torch.no_grad():
        patch = backbone_model(inp)  # [P, feat_dim]
    # build graph
    data, (gh, gw) = build_patch_graph_from_features(patch.cpu(), grid_h=None, grid_w=None, add_positional=True)
    data.x = data.x.to(device)
    data.edge_index = data.edge_index.to(device)

    with torch.no_grad():
        recon = gat_model(data.x, data.edge_index)
    # compute per-node MSE between recon_feat and original feat
    feat_dim = patch.shape[1]
    recon_feat = recon[:, :feat_dim]
    orig_feat = data.x[:, :feat_dim]
    # per-node MSE
    per_node_mse = torch.mean((recon_feat - orig_feat)**2, dim=1)  # [P,]
    per_node_mse = per_node_mse.cpu().numpy()

    # reshape to grid and upsample to image size
    P = per_node_mse.shape[0]
    # infer grid dims
    sq = int(math.sqrt(P))
    if sq*sq == P:
        gh = gw = sq
    else:
        # fallback: try to use previously returned gh, gw
        gh, gw = gh, gw

    segm_map = per_node_mse.reshape(1, 1, gh, gw).astype(np.float32)  # 1x1xhxw
    segm_map_t = torch.tensor(segm_map)
    segm_up = F.interpolate(segm_map_t, size=up_size, mode='bilinear', align_corners=False)
    segm_up = segm_up.squeeze().cpu().numpy()
    # normalize to 0..1
    segm_up = (segm_up - segm_up.min()) / (segm_up.max() - segm_up.min() + 1e-8)

    return segm_up, per_node_mse

good_img = Image.open("/content/Carpet/carpet/test/good/001.png").convert("RGB")
def_img = Image.open("/content/Carpet/carpet/test/color/000.png").convert("RGB")

for label, img in [("Good", good_img), ("Defective", def_img)]:
    segm_map, per_patch = gat_ae_infer_image_heatmap(img, backbone, gat_model)
    anomaly_score = np.mean(per_patch)
    print(f"{label} Image Anomaly Score: {anomaly_score:.4f}")

# load trained model if needed
feature = backbone(image)
print(feature.shape)
# Define patch dimension for GAT model
patch_dim = feature.shape[1]
gat_model = GATAutoEncoder(in_dim=patch_dim+2).to(device)
#gat_model.load_state_dict(torch.load('gat_ae.pth'))
from PIL import Image
img = Image.open('/content/Carpet/carpet/test/color/000.png').convert('RGB')
segm_up, per_node = gat_ae_infer_image_heatmap(img, backbone, gat_model, up_size=(224,224))

# visualize
import matplotlib.pyplot as plt
plt.imshow(segm_up, cmap='jet')
plt.title('GAT-AE anomaly heatmap (normalized)')
plt.colorbar()
plt.show()

def image_level_score_from_heatmap(segm_up, aggregation='max'):
    if aggregation == 'max':
        return float(segm_up.max())
    elif aggregation == 'mean':
        return float(segm_up.mean())
    else:
        return float(segm_up.max())

# example
img_score = image_level_score_from_heatmap(segm_up, aggregation='max')
print("Image-level anomaly score:", img_score)

# Normal image (should give ~0)
img_good = Image.open('/content/Carpet/carpet/train/good/000.png').convert('RGB')
_, score_good = gat_ae_infer_image_heatmap(img_good, backbone, gat_model)
print("Good image score:", score_good)

# Defective image (should give ~1)
img_def = Image.open('/content/Carpet/carpet/test/color/001.png').convert('RGB')
_, score_def = gat_ae_infer_image_heatmap(img_def, backbone, gat_model)
print("Defective image score:", score_def)

import json, random, numpy as np, torch

cfg = dict(
    lr=5e-4,
    epochs=25,
    batch=8,
    device=str(device),
    feat_dim=1536     # <--- replace patch.shape[1] with 1536 (your feature dim)
)

with open('config.json','w') as f:
    json.dump(cfg, f, indent=2)

# set seeds for reproducibility
seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

from sklearn.metrics import roc_auc_score, roc_curve, auc
y_true = np.array(y_true)   # 0 normal, 1 anomaly
y_score = np.array(y_score) # image-level scores
roc_auc = roc_auc_score(y_true, y_score)
fpr, tpr, th = roc_curve(y_true, y_score)
print("AUC:", roc_auc)

import torch
import numpy as np
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix

# Example: replace these with your actual predictions and true labels
# Suppose your test set has 4 defect types + 1 good
class_names = ['good', 'cut', 'hole', 'color', 'thread']

# Example true vs predicted labels
y_true = ['good','cut','hole','color','hole','good','cut','thread','thread','color']
y_pred = ['good','cut','hole','color','good','good','cut','thread','thread','color']

# Compute metrics per class
metrics_data = []
for cls in class_names:
    y_true_bin = [1 if y == cls else 0 for y in y_true]
    y_pred_bin = [1 if y == cls else 0 for y in y_pred]
    precision = precision_score(y_true_bin, y_pred_bin, zero_division=0)
    recall = recall_score(y_true_bin, y_pred_bin, zero_division=0)
    f1 = f1_score(y_true_bin, y_pred_bin, zero_division=0)
    acc = accuracy_score(y_true_bin, y_pred_bin)
    metrics_data.append([cls, precision, recall, f1, acc])

# Create a table
df_metrics = pd.DataFrame(metrics_data, columns=['Defect Type', 'Precision', 'Recall', 'F1-Score', 'Accuracy'])
df_metrics.set_index('Defect Type', inplace=True)

# Round to 3 decimals and display
df_metrics = df_metrics.round(3)
print(df_metrics)

# 📊 Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# Example labels — replace with your actual test labels & predictions
class_names = ['good', 'cut', 'hole', 'color', 'thread']
y_true = ['good','cut','hole','color','hole','good','cut','thread','thread','color']
y_pred = ['good','cut','hole','color','good','good','cut','thread','thread','color']

# ✅ Compute per-class metrics
metrics_data = []
for cls in class_names:
    y_true_bin = [1 if y == cls else 0 for y in y_true]
    y_pred_bin = [1 if y == cls else 0 for y in y_pred]
    precision = precision_score(y_true_bin, y_pred_bin, zero_division=0)
    recall = recall_score(y_true_bin, y_pred_bin, zero_division=0)
    f1 = f1_score(y_true_bin, y_pred_bin, zero_division=0)
    acc = accuracy_score(y_true_bin, y_pred_bin)
    metrics_data.append([cls, precision, recall, f1, acc])

# 📋 Create a DataFrame
df_metrics = pd.DataFrame(metrics_data, columns=['Defect Type', 'Precision', 'Recall', 'F1-Score', 'Accuracy'])
df_metrics.set_index('Defect Type', inplace=True)
df_metrics = df_metrics.round(3)

# 🧷 Display styled table
styled = df_metrics.style.background_gradient(cmap='Blues').set_caption("📊 Per-Defect Metrics Summary")
display(styled)

# 📉 Bar Plot Visualization
plt.figure(figsize=(10,6))
df_metrics.plot(kind='bar', figsize=(10,6))
plt.title("Performance Metrics per Defect Type", fontsize=14, weight='bold')
plt.ylabel("Score")
plt.ylim(0,1.1)
plt.xticks(rotation=0)
plt.legend(loc='lower right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 🔥 Confusion Matrix
cm = confusion_matrix(y_true, y_pred, labels=class_names)
plt.figure(figsize=(7,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Purples', xticklabels=class_names, yticklabels=class_names)
plt.title("Confusion Matrix", fontsize=14, weight='bold')
plt.xlabel("Predicted Labels")
plt.ylabel("True Labels")
plt.show()

import torch
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def infer_image_anomaly(image_path, backbone, gat_model):
    """
    Infers anomaly score for a single image and returns heatmap + image-level score.
    """
    img = Image.open(image_path).convert("RGB")

    # Get patch-level anomaly map (heatmap) and patch scores
    heatmap, patch_scores = gat_ae_infer_image_heatmap(img, backbone, gat_model)

    # Convert patch_scores → tensor if not already
    patch_scores = torch.tensor(patch_scores).float()

    # Compute image-level anomaly score (mean of all patches)
    image_score = patch_scores.mean().item()

    return heatmap, image_score


# ---------------------- Run Verification ----------------------

print("⚙️ Device being used:", device)

img_good_path = "/content/Carpet/carpet/train/good/000.png"
_, score_good = infer_image_anomaly(img_good_path, backbone, gat_model)
print(f"✅ Good Image Anomaly Score: {score_good:.4f} (Expected ≈ 0.2–0.5)")

img_def_path = "/content/Carpet/carpet/test/color/000.png"
_, score_def = infer_image_anomaly(img_def_path, backbone, gat_model)
print(f"🚨 Defective Image Anomaly Score: {score_def:.4f} (Expected ≈ 0.8–1.2)")